logging:
  level:
    org.springframework: ERROR
    com.gov: INFO
spring:
   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: update
   datasource:
     url: jdbc:postgresql://localhost:5432/accounts
     username: postgres
     password: password
     initialization-mode: always
     platform: postgres

security:
  oauth2:
    client:
      accessTokenUri: http://inv.grp.gov.bd:8011/auth-service/sec/master/authentication/v1/login
      clientId: grp-web-portal
      clientSecret: 123456