server:
  port: 8080

logging:
  level:
    org.springframework: ERROR
    com.gov: INFO
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 0b8a0780fc464b904433
      clientSecret: 9be445cacac27299ce50f0bc77db618a5daae1dd
      redirect_uri: http://localhost:8080
      userAuthorizationUri: https://github.com/login/oauth/authorize
      accessTokenUri: https://github.com/login/oauth/access_token
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
spring:
   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         jdbc:
           lob:
             non_contextual_creation: true
     hibernate:
       ddl-auto: update
   datasource:
     url: jdbc:postgresql://localhost:5432/accounts
     username: postgres
     password: password
     initialization-mode: always
     platform: postgres